record:
  repo_id: &repo_id "shenzhaolong/test_grasp" 
  # repo_id: &repo_id "scylearning/pick_greencube_into_trashbin" 
  # Suggested format: <hf_username>/<description>, description = task.description -> Verb_SourceObject_prep_TargetObject
  # e.g. Pick up the green cube and put it into the trash bin -> pick_greencube_into_trashbin
  debug: False # if True, robot will not execute any actions, but gripper can still be controlled
  user_notes:  # any additional notes about the dataset
  fps: 15 # dataset and camera frame rate

  teleop:
    control_mode: "isoteleop"
    dynamixel_config:
      port: "/dev/serial/by-id/usb-1a86_USB_Serial-if00-port0"
      # hardware_offsets: [0, 0, 0, 0, 0, 0, 0] # The Calibration offsets between the master and the slave robot
      hardware_offsets: [-0.12183455210997171, -0.002845966063342931, -0.06250428305273764, -2.0498354593763044, 0.05259129256457092, 1.9984585428810417, -0.9046528345737315] 
      use_gripper: &use_gripper True # whether the slave robot can use gripper
      joint_ids: [0, 1, 2, 3, 4, 5, 6]
      joint_offsets: [6.283, 3.142, 6.283, 4.712, 4.712, 6.283, 2.496]
      joint_signs: [1, 1, 1, 1, 1, -1, 1]
      gripper_config: [7, 0.9664079, 1.9404857] # id, min, max
      
  robot:
    # ip: &ip "172.16.0.2" # robot ip
    ip: &ip "192.168.1.104" # NUC ip
    use_gripper: *use_gripper
    close_threshold: 0.7 # threshold to determine gripper open/close
    gripper_bin_threshold: 0.98 # threshold to determine gripper is closed
    # gripper_port: &gripper_port "/dev/franka_left_gripper" # gripper_port
    gripper_reverse: False  # If gripper moves opposite, flip this value
    gripper_max_open: 0.0801 # gripper max open width in meters

  task:
    # description: "Pick up the green cube and put it into the trash bin." # task description
    description: "test by shenzhaolong" # task description
    num_episodes: 10 # number of episodes to record
    display: True # Whether to display the data during recording
    resume: False # whether to resume from an existing dataset
    resume_dataset: shenzhaolong/test_dataset_20251205_v02 # dataset to resume from if resume is True

  time:
    episode_time_sec: 6000 # max time per episode in seconds
    reset_time_sec: 6000 # max time to reset between episodes in seconds
    save_meta_period: 1 # Save metadata after every N episodes

  cameras:
    wrist_cam_serial: "339322074423" # wrist camera serial number
    exterior_cam_serial: "243322071821" # exterior camera serial number
    width: 424 # 640 424
    height: 240 # 360 240

  storage:
    push_to_hub: False # whether to push the dataset to your huggingface repo after recording

replay:
  dataset_name: shenzhaolong/test_grasp_20251216_v06
  episode_idx: 0 # episode index to replay
  robot:
    ip: *ip
    # gripper_port: *gripper_port

visualize:
  dataset_name: shenzhaolong/test_grasp_20251216_v06
  episode_index: 0 # episode index to visualize
