record:
  repo_id: &repo_id "szl/pick_all_bluewcubes" 
  # repo_id: &repo_id "scylearning/pick_greencube_into_trashb
  # Suggested format: <hf_username>/<description>, description = task.description -> Verb_SourceObject_prep_TargetObject
  # e.g. Pick up the green cube and put it into the trash bin -> pick_greencube_into_trashbin
  debug: 0 # if True, robot will not execute any actions, but gripper can still be controlled
  user_notes:  # any additional notes about the dataset
  fps: 15 # dataset and camera frame rate
  control_mode: &control_mode "isoteleop" # "isoteleop" or "spacemouse"
  run_mode: "run_record" # "run_record" or "run_policy" or "run_mix"

  teleop:
    control_mode: *control_mode 
    dynamixel_config:
      port: "/dev/serial/by-id/usb-1a86_USB_Serial-if00-port0"
      # hardware_offsets: [0, 0, 0, 0, 0, 0, 0] # The Calibration offsets between the master and the slave robot
      hardware_offsets: [-0.12183455210997171, -0.002845966063342931, -0.06250428305273764, -2.0498354593763044, 0.05259129256457092, 1.9984585428810417, -0.9046528345737315] 
      use_gripper: &use_gripper True # whether the slave robot can use gripper
      joint_ids: [0, 1, 2, 3, 4, 5, 6]
      joint_offsets: [6.283, 3.142, 0.0, 4.712, 4.712, 6.283, 2.496]
      joint_signs: [1, 1, 1, 1, 1, -1, 1]
      gripper_config: [7, 0.9664079, 1.9404857] # id, min, max
    spacemouse_config:
      channel_ids: [0, 1, 2, 3, 4, 5]
      channel_signs: [-1, -1, 1, -1, -1, 1]
      use_gripper: *use_gripper # whether the spacemouse robot can use gripper
      pose_scaler: [0.03, 0.15] # scaler for spacemouse actions [position, attitude]
    placo:
      visualize_placo: False
      placo_dt: 0.01
      robot_urdf_path: assets/franka_urdf/fr3v2_franka_hand.urdf
      
  robot:
    # ip: &ip "172.16.0.2" # robot ip
    ip: &ip "192.168.110.15" # NUC ip
    use_gripper: *use_gripper
    close_threshold: 0.7 # threshold to determine gripper open/close
    gripper_bin_threshold: 0.98 # threshold to determine gripper is closed
    # gripper_port: &gripper_port "/dev/franka_left_gripper" # gripper_port
    gripper_reverse: False  # If gripper moves opposite, flip this value
    gripper_max_open: 0.0801 # gripper max open width in meters

  policy:
    type: "diffusion"  # 策略类型 (act, diffusion)
    device: "cuda"  # 运行设备 (cuda, cpu)
    push_to_hub: False  # 禁用模型推送
    pretrained_path: "/home/deepcybo/lerobot/franka_workspace/outputs/train/diffusion_test7/checkpoints/last/pretrained_model"  
    # 预训练模型路径下要包括config.json

  task:
    # description: "Pick up the green cube and put it into the trash bin." # task description
    description: "pick up all blue cubes and put them into the brown basket" # task description
    num_episodes: 30 # number of episodes to record
    display: True # Whether to display the data during recording
    resume: false # whether to resume from an existing dataset
    resume_dataset: szl/pick_all_yellowcubes_20260203_v01 # dataset to resume from if resume is True
  time:
    episode_time_sec: 6000 # max time per episode in seconds
    reset_time_sec: 6000 # max time to reset between episodes in seconds
    save_meta_period: 1 # Save metadata after every N episodes

  cameras:
    wrist_cam_serial: "344322074412" # wrist camera serial number
    exterior_cam_serial: "243322071821" # exterior camera serial number 243322071821 339322074423
    width: 424 # 640 424
    height: 240 # 360 240

  storage:
    push_to_hub: False # whether to push the dataset to your huggingface repo after recording

replay:
  dataset_name: shenzhaolong/pick_carrot_20260203_v01
  episode_idx: 10 # episode index to replay
  robot:
    ip: *ip
    # gripper_port: *gripper_port
  control_mode: *control_mode 

visualize:
  dataset_name: szl/pick_all_objects_complete
  episode_index: 212 # episode index to visualize




