train:
  dataset:
    repo_id: "physbrain3/pick_and_place_merged"
  # 指向包含数据集 repo 的本地目录（要包含 repo_id 子目录），
  # 例如本地缓存路径下的 physbrain3/pick_and_place_merged
    root: "/home/deepcybo/.cache/huggingface/lerobot/physbrain3/pick_and_place_merged"

  env:

  policy:
    type: "diffusion"
    device: "cuda"
    repo_id: "shenzhaolong/diffusion_policy"
    push_to_hub: false  # 禁用模型推送

  output_dir: "outputs/train/diffusion_test7"
  job_name: "diffusion_policy_test7"

  resume: False
  seed: 1000
  # Number of workers for the dataloader.
  num_workers: 4
  batch_size: 8
  steps: 200_00
  eval_freq: 20_00
  log_freq: 200
  save_checkpoint: True
  # Checkpoint is saved every `save_freq` training iterations and after the last training step.
  save_freq: 10_000
  use_policy_training_preset: True

  eval: 
    n_episodes: 10
    batch_size: 8

  wandb: 
    enable: True
    project: "lerobot"
    # entity: "your-wandb-username"  # 改为您的 WandB 用户名，或注释掉使用默认
    # notes: "训练备注"
    # run_id: "自定义运行ID"
    mode: "online"  # Allowed values: 'online', 'offline' 'disabled'. Defaults to 'online"